import logging
import os

GRAPH_API_VERSION = "v21.0"

_LOG_LEVEL_NAME = os.getenv("LOG_LEVEL", "INFO").upper()
LOG_LEVEL = getattr(logging, _LOG_LEVEL_NAME, logging.INFO)
PROCESSED_IDS_MAX = 2000

VERIFY_TOKEN = os.getenv("VERIFY_TOKEN", "")
WHATSAPP_ACCESS_TOKEN = os.getenv("WHATSAPP_ACCESS_TOKEN", "")
WHATSAPP_PHONE_NUMBER_ID = os.getenv("WHATSAPP_PHONE_NUMBER_ID", "")
WHATSAPP_APP_SECRET = os.getenv("WHATSAPP_APP_SECRET", "")

SLACK_BOT_TOKEN = os.getenv("SLACK_BOT_TOKEN", "")
SLACK_SIGNING_SECRET = os.getenv("SLACK_SIGNING_SECRET", "")

GMAIL_CLIENT_ID = os.getenv("GMAIL_CLIENT_ID", "")
GMAIL_CLIENT_SECRET = os.getenv("GMAIL_CLIENT_SECRET", "")
GMAIL_REFRESH_TOKEN = os.getenv("GMAIL_REFRESH_TOKEN", "")
GMAIL_MAILBOX_EMAIL = os.getenv("GMAIL_MAILBOX_EMAIL", "")
GMAIL_PUBSUB_TOPIC = os.getenv("GMAIL_PUBSUB_TOPIC", "")
GMAIL_PUSH_AUDIENCE = os.getenv("GMAIL_PUSH_AUDIENCE", "")
GMAIL_WATCH_SECRET = os.getenv("GMAIL_WATCH_SECRET", "")
GMAIL_STATE_PATH = os.getenv("GMAIL_STATE_PATH", ".gmail_state.json")

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_AGENT_MODEL = os.getenv("OPENAI_AGENT_MODEL", "gpt-4o-mini")
OPENAI_TRANSCRIPTION_MODEL = os.getenv("OPENAI_TRANSCRIPTION_MODEL", "whisper-1")
OPENAI_TRANSCRIPTION_ROMANIZE_MODEL = os.getenv(
    "OPENAI_TRANSCRIPTION_ROMANIZE_MODEL", "gpt-4o-mini"
)
